import type {Metadata} from 'next';
import { Poppins } from 'next/font/google'; // Import Poppins
import './globals.css';
import { Toaster } from "@/components/ui/toaster"

// Configure Poppins font
const poppins = Poppins({
  variable: '--font-poppins',
  weight: ['400', '500', '600'], // Specify needed weights from guidelines
  subsets: ['latin'],
  display: 'swap', // Optional: improve font loading
});


export const metadata: Metadata = {
  title: 'JRiley Park & Pay', // Removed extra text from title
  description: 'Generated by Firebase Studio',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Apply Poppins font class to the body */}
      <body className={`${poppins.variable} font-sans antialiased`}> {/* Use font-sans which should be mapped to Poppins now */}
        {children}
        <Toaster />
      </body>
    </html>
  );
}
